# -*- coding: utf-8 -*-
"""解析 extracted/pig_compendium.txt，生成 Go 数据文件 data_gen.go

数据格式（正文从第 8 页开始）：
    <序号>
    <序号>. 名称(slug)
    描述：xxx          （可能跨行）
    性格分析：xxx      （可能跨行）
    <页码>             （页末）
    ===== 第 N 页 =====
"""
import json
import os
import re

SRC = r"d:\Programs\daily-piggy\extracted\pig_compendium.txt"
OUT = r"d:\Programs\daily-piggy\data_gen.go"
IMG_DIR = r"d:\Programs\daily-piggy\extracted\images"

TITLE_RE = re.compile(r"^===== 第 (\d+) 页 =====")
SEQ_RE = re.compile(r"^(\d+)$")
ITEM_RE = re.compile(r"^(\d+)\.\s*(.+?)\(([^()]*)\)\s*$")

pigs = []
cur = None
in_body = False  # 跳过目录页

with open(SRC, encoding="utf-8") as f:
    lines = f.readlines()

i = 0
n = len(lines)
while i < n:
    line = lines[i].rstrip("\n")
    m = TITLE_RE.match(line)
    if m:
        pageno = int(m.group(1))
        if pageno >= 8:
            in_body = True
        else:
            in_body = False
        i += 1
        continue

    if not in_body:
        i += 1
        continue

    # 页码行：后跟 "===== 第" 或文件结束 → 跳过
    sm = SEQ_RE.match(line)
    if sm and i + 1 < n:
        nxt = lines[i + 1].rstrip("\n")
        if TITLE_RE.match(nxt):
            i += 1
            continue
        # 条目序号：下一行是 "N. 名称(slug)"
        im = ITEM_RE.match(nxt)
        if im and int(im.group(1)) == int(sm.group(1)):
            # 新条目开始
            cur = {"ID": int(im.group(1)), "Name": im.group(2).strip(),
                   "Slug": im.group(3).strip(), "Desc": "", "Analysis": ""}
            pigs.append(cur)
            i += 2
            continue
        # 尾部页码：纯数字行，后跟 "===== 第" 或下一个条目 → 跳过
        # （需要往后找下一个非空行判断）
        j = i + 1
        while j < n and not lines[j].strip():
            j += 1
        if j < n:
            after = lines[j].rstrip("\n")
            if TITLE_RE.match(after) or ITEM_RE.match(after) or SEQ_RE.match(after):
                i += 1
                continue
    # 非条目行（描述/性格分析，可能跨行，也可能同行）
    if cur is not None:
        if line.startswith("描述："):
            rest = line[len("描述："):]
            # 处理"描述：xxx 性格分析：yyy"同行的情况（分隔符可能是空格/NUL等）
            idx = rest.find("性格分析：")
            if idx > 0:
                cur["Desc"] = rest[:idx].rstrip(" \x00")
                cur["Analysis"] = rest[idx + len("性格分析："):]
            else:
                cur["Desc"] = rest
        elif line.startswith("性格分析："):
            cur["Analysis"] = line[len("性格分析："):]
        elif line.strip():
            # 续行：追加到最近的非空字段（描述或性格分析）
            if cur["Analysis"]:
                cur["Analysis"] += "\n" + line
            elif cur["Desc"]:
                cur["Desc"] += "\n" + line
    i += 1

# 校验
print(f"解析到 {len(pigs)} 条猪猪")
missing = [p for p in pigs if not p["Desc"] or not p["Analysis"]]
print(f"缺字段条目: {len(missing)}")
for p in missing:
    print("  ", p)
ids = [p["ID"] for p in pigs]
print("ID 范围:", min(ids), "-", max(ids), "连续:", ids == list(range(1, len(pigs) + 1)))

# 图片映射校验：img_NNN_pXX.jpg 中 NNN 应与猪猪 ID 一一对应
img_files = sorted(os.listdir(IMG_DIR))
img_ids = sorted(int(re.match(r"img_(\d+)", f).group(1)) for f in img_files)
print(f"图片 {len(img_files)} 张, 序号范围 {img_ids[0]}-{img_ids[-1]}, 与猪猪 ID 一致: {img_ids == ids}")

# 生成 Go 源码
def go_str(s):
    return json.dumps(s, ensure_ascii=False)

out = ['// Code generated by gen_data.py; DO NOT EDIT.', '',
       'package piggy', '',
       'import "strconv"', '',
       '// Pig 表示一只猪猪条目。', 'type Pig struct {',
       '\tID       int    // 序号 1-149',
       '\tName     string // 中文名',
       '\tSlug     string // 英文标识',
       '\tDesc     string // 描述',
       '\tAnalysis string // 性格分析',
       '}', '',
       '// ImageName 返回该猪猪对应的嵌入图片文件名。',
       'func (p *Pig) ImageName() string {',
       '\treturn "img_" + pad3(p.ID) + ".jpg"',
       '}', '',
       'func pad3(n int) string {',
       '\ts := strconv.Itoa(n)',
       '\tfor len(s) < 3 {',
       '\t\ts = "0" + s',
       '\t}',
       '\treturn s',
       '}', '',
       '// pigs 全部 149 种猪猪（顺序即序号）。',
       'var pigs = []Pig{']
for p in pigs:
    out.append('\t{ID: %d, Name: %s, Slug: %s, Desc: %s, Analysis: %s},' % (
        p["ID"], go_str(p["Name"]), go_str(p["Slug"]),
        go_str(p["Desc"]), go_str(p["Analysis"])))
out.append('}')

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print("已生成:", OUT)
